repos:
        #-   repo: https://github.com/humitos/powrap
        #    rev: master
        #    hooks:
        #    -   id: powrap

# This one requires package ``hunspell-es_es`` in Archlinux
-   repo: https://github.com/humitos/pospell
    rev: pre-commit
    hooks:
    -   id: pospell
        args: ['--personal-dict', 'dict', '--modified', '--language', 'es_ES', '--language', 'es_AR']

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: file-contents-sorter
        files: dict
