repos:
-   repo: https://github.com/JulienPalard/powrap
    rev: master
    hooks:
    -   id: powrap
-   repo: local
    hooks:
    -   id: merge-dicts
        name: merge-dicts
        entry: ./scripts/merge-dicts.sh
        language: script
# This one requires package ``hunspell-es_es`` in Archlinux
-   repo: https://github.com/JulienPalard/pospell
    rev: v1.0.9
    hooks:
    -   id: pospell
        args: ['--personal-dict', 'dict.txt', '--language', 'es_ES']
