repos:
-   repo: https://github.com/JulienPalard/powrap
    rev: v0.4.0
    hooks:
    -   id: powrap
-   repo: local
    hooks:
    -   id: merge-dicts
        name: merge-dicts
        entry: python ./scripts/create_dict.py
        language: python
# This one requires package ``hunspell-es_es`` in Archlinux
-   repo: https://github.com/AFPy/pospell
    rev: v1.1
    hooks:
    -   id: pospell
        args: ['--personal-dict', 'dict.txt', '--language', 'es_ES', '--language', 'es_AR']
