language: python
dist: bionic
python: 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-es
install:
  - make setup
  - pospell --version
  - powrap --version
script:
  - powrap --check --quiet **/*.po
  - pospell -p dict -l es_AR -l es_ES **/*.po
  - make dict_dups
  - make build
branches:
  only:
  - /^3\.\d$/
