language: python
dist: bionic
python: 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-es
install:
  - make setup
  - pospell --version
  - powrap --version
script:
  - powrap --check --quiet **/*.po
  - awk 1 dict dictionaries/*.txt > dict.txt
  - pospell -p dict.txt -l es_AR -l es_ES **/*.po
  - make build
branches:
  only:
  - /^3\.\d$/
